{{- $fullName := .Values.gitlab.app -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}"
  labels:
{{ include "chart.labels" . | indent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
    {{- if and (eq $key "encKey") (empty $value) }}
  {{ $key }}: {{ randAlphaNum 32 | b64enc | quote }}
    {{- else }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- if eq .Values.gitlab.env "production" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-registry"
  labels:
{{ include "chart.labels" . | indent 4 }}
type: Opaque
stringData:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}